scrape_configs:
  - job_name: 'micro-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.94:9081', '192.168.1.94:9082', '192.168.1.94:9083' ]

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.94:8080' ]

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '192.168.1.94:9999' ]