services:
  configservice:
    build:
      context: configservice
      dockerfile: Dockerfile
    image: config-service
    ports:
      - 8888:8888
    volumes:
      - C:/Users/DINHCUONG/Documents/GitHub/springcloud/tutorials-2024/section8/configservice/src/main/resources/shared:/git-repo
    env_file:
      - local.env

  discoveryservice:
    build:
      context: discoveryservice
      dockerfile: Dockerfile
    image: discovery-service
    ports:
      - 9999:9999
    restart: on-failure
    env_file:
      - local.env

  monitoradmin:
    build:
      context: monitoradmin
      dockerfile: Dockerfile
    image: monitor-service
    ports:
      - 9001:9001
    restart: on-failure
    env_file:
      - local.env

  gatewayservice:
    build:
      context: gatewayservice
      dockerfile: Dockerfile
    image: gateway-service
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - local.env

  accountservice:
    build:
      context: accountservice
      dockerfile: Dockerfile
    image: account-service
    ports:
      - 9081:9081
    restart: on-failure
    env_file:
      - local.env

  statisticservice:
    build:
      context: statisticservice
      dockerfile: Dockerfile
    image: statistic-service
    ports:
      - 9082:9082
    restart: on-failure
    env_file:
      - local.env

  notificationservice:
    build:
      context: notificationservice
      dockerfile: Dockerfile
    image: notification-service
    ports:
      - 9083:9083
    restart: on-failure
    env_file:
      - local.env

  #keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9000:8080
    restart: on-failure
    command:
      - start-dev
    env_file:
        - keycloak.env

  fereact:
    build:
      context: fereact
      dockerfile: Dockerfile
      args:
        REACT_APP_RESOUCE_URI: http://192.168.1.94:8080
        REACT_APP_KEYCLOAK_URI: http://192.168.1.94:9000/realms/springcloud
        REACT_APP_KEYCLOAK_CLIENT_SCOPE: read write openid
        REACT_APP_KEYCLOAK_CLIENT_ID: jmaster
        REACT_APP_KEYCLOAK_CLIENT_SECRET: tgqLoAfmtzhrZxHNi8ORoY8ThNdyVCnN
        REACT_APP_KEYCLOAK_ADMIN_URI: http://192.168.1.94:9000/admin/realms/springcloud/
    image: fereact
    ports:
      - 3000:80

  zipkinervice:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-grafana/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "4000:3000"
    restart: unless-stopped
    volumes:
      - ./prometheus-grafana/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources